[package]
name = "carapace"
version = "0.0.0"
authors = ["Nugine <nugine@foxmail.com>"]
edition = "2018"
description = "code runner for online judge"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.60"
rlimit = "0.2.1"
syscallz = { path = "/home/nugine/project/syscallz-rs" }
