[package]
name = "carapace"
version = "0.0.0"
authors = ["Nugine <nugine@foxmail.com>"]
edition = "2018"
description = "code runner for online judge"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.14.1"
libc = "0.2.60"
rlimit = "0.2.1"
syscallz = "0.11.4"
rusty-fork = "0.2.2"